### ISSUE TITLE
Error type of props

### ISSUE THREAD

**Issue by chuckWu1989** [dmtrKovalenko/material-ui-datetimepicker#13]
Hello:
I had found there was type error in DatePicker and TimePicker. When building the demo codes, console would show warning said: "Failed prop type: Invalid prop `TimePicker` of type `function` supplied to `DateTimePicker`, expected `object`.". Same message with DatePicker. I tried to modify the source code to propTypes.func.isRequired then the warning was gone. Please help for checking if this issue is existed or not. Thanks.
By the way, this project was an awesome job. It saved me a lot of time. Thanks for contribution of authors.

**Comment by dmtrKovalenko** [comment]
Hello, thank you for help!
Would you like to open a pull request?

**Comment by chuckWu1989** [comment]
Hello:
Sure, I would PR later. Thanks.

Cheers,
Chuck

**Comment by dmtrKovalenko** [comment]
:sunglasses: Fixed in [v1.0.1](https://github.com/dmtrKovalenko/material-ui-datetimepicker/tree/1.0.1)
