### ISSUE TITLE
Textfield Full width problem

### ISSUE THREAD

**Issue by chuckWu1989** [dmtrKovalenko/material-ui-datetimepicker#14]
Hello:
When I tried to set textfield as fullwidth, I found the icon of closing would display at wrong location (It would fell-off to the second row. I suggested to add some containers to package the datetimepicker and closing icon. For example:
`<div className="col-xs-10"><datetimePicker /></div><div className="col-xs-2><Icon /></div>"`
How do you think?

**Comment by dmtrKovalenko** [comment]
:sunglasses: Fixed in [v1.0.1](https://github.com/dmtrKovalenko/material-ui-datetimepicker/tree/1.0.1)
