### ISSUE TITLE
defaultTime error

### ISSUE THREAD

**Issue by chuckWu1989** [dmtrKovalenko/material-ui-datetimepicker#15]
Hello:
When I tried to set default time to datetime picker, I found timepicker would always the current time instead of the time I set. I tried to modify source codes as:
`<TimePicker **initialTime**=... />`
Then it worked. Please checked if it was right. Thanks.

**Comment by dmtrKovalenko** [comment]
:sunglasses: Fixed in [v1.0.1](https://github.com/dmtrKovalenko/material-ui-datetimepicker/tree/1.0.1)
