### ISSUE TITLE
clearIcon works even after disabled the field

### ISSUE THREAD

**Issue by ahmedtehseen** [dmtrKovalenko/material-ui-datetimepicker#16]
Hi mate, first thing to mention this expansion really helps me.

I want to know that after disabled the field is there any way to avoid the clearIcon button because when I give the disabled property to the field it will only disable the date or time field but clearIcon remains accessible.
I also set the clearIcon property to null but it only hides the clearIcon  not removes it from there we can still clear the field after clicking the right corner of it.

Thanks.

**Comment by dmtrKovalenko** [comment]
Hi, thanks for your feedback, will fix that asap.

**Comment by ahmedtehseen** [comment]
hi, thanks that would be appreciated however I've done a small tweak here to deal with this.
I've set the clearIconStyle to { display: 'none' } and it works but it's not a real fix.

**Comment by dmtrKovalenko** [comment]
Fixed in [v1.0.2](https://github.com/dmtrKovalenko/material-ui-datetimepicker/releases/tag/v1.0.2)
